Update dependencies
Signed-off-by: dcillera <dcillera@redhat.com>

diff --git a/ossm/vendor/com_github_grpc_grpc/tools/internal_ci/helper_scripts/prepare_build_macos_rc b/ossm/vendor/com_github_grpc_grpc/tools/internal_ci/helper_scripts/prepare_build_macos_rc
--- a/ossm/vendor/com_github_grpc_grpc/tools/internal_ci/helper_scripts/prepare_build_macos_rc
+++ b/ossm/vendor/com_github_grpc_grpc/tools/internal_ci/helper_scripts/prepare_build_macos_rc
@@ -58,6 +58,8 @@ brew config
 if $is_sonoma; then
   brew install cmake
   brew install gnupg
+  export PATH="/opt/homebrew/bin::${PATH}"
+  cmake --version
 fi
 
 # Add GCP credentials for BQ access
@@ -72,7 +74,9 @@ if [ -n "$KOKORO_GITHUB_PULL_REQUEST_NUMBER" ]; then
   export RUN_TESTS_FLAGS="--filter_pr_tests --base_branch origin/$KOKORO_GITHUB_PULL_REQUEST_TARGET_BRANCH $RUN_TESTS_FLAGS"
 fi
 
-if [ "${PREPARE_BUILD_INSTALL_DEPS_RUBY}" == "true" ]
+# Changes not needed for sonoma(Already have version available)
+# cleanup this once migration complete
+if [ "${PREPARE_BUILD_INSTALL_DEPS_RUBY}" == "true" ] && ! $is_sonoma;
 then
   # Workaround for https://github.com/rvm/rvm/issues/5133
   export CURL_CA_BUNDLE=$(pwd)/etc/roots.pem
@@ -136,6 +140,9 @@ fi
 
 if [ "${PREPARE_BUILD_INSTALL_DEPS_PYTHON}" == "true" ]
 then
+  # add /usr/local/bin to path to override built in Python version
+  export PATH="/usr/local/bin::${PATH}"
+
   # python
   time pip install --user -r $DIR/requirements.macos.txt
   time pip install --user --upgrade virtualenv Mako tox setuptools==44.1.1 twisted
@@ -179,6 +186,14 @@ then
     shasum -c /tmp/python_installer_checksum.sha256
     time sudo installer -pkg ./python-3.13.0rc2-macos11.pkg -target /
   fi
+
+  # Install Python 3.14 if it doesn't exist
+  if [ ! -f "/usr/local/bin/python3.14" ]; then
+    time curl -O https://www.python.org/ftp/python/3.14.0/python-3.14.0rc1-macos11.pkg
+    echo "05b17ddad5a7c3641d0ecfe5ccf3a97f89c1757e  python-3.14.0rc1-macos11.pkg" > /tmp/python_installer_checksum.sha256
+    shasum -c /tmp/python_installer_checksum.sha256
+    time sudo installer -pkg ./python-3.14.0rc1-macos11.pkg -target /
+  fi
 fi
 
 if [ "${PREPARE_BUILD_INSTALL_DEPS_CSHARP}" == "true" ]
@@ -219,10 +234,33 @@ then
   php --version
 
   if $is_sonoma; then
-    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-    php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
+    # See https://getcomposer.org/download.
+    # Composer installer checksum verification: https://composer.github.io/pubkeys.html
+
+    # Dynamically load the current checksum per
+    # https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
+    curl --retry 3 -sL -o composer-installer.sig https://composer.github.io/installer.sig
+    EXPECTED_COMPOSER_SHA384_SUM="$(cat composer-installer.sig)"
+    if [[ -z "${EXPECTED_COMPOSER_SHA384_SUM}" ]]; then
+      echo "Failed to load latest composer installer checksum" >&2
+      exit 1
+    fi
+
+    curl --retry 3 -sL -o composer-setup.php https://getcomposer.org/installer
+    ACTUAL_COMPOSER_SHA384_SUM="$(sha384sum composer-setup.php | cut -w -f1)"
+
+    echo "Expected composer-setup.php sha384 sum: ${EXPECTED_COMPOSER_SHA384_SUM}"
+    echo "Downloaded composer-setup.php sha384 sum: ${ACTUAL_COMPOSER_SHA384_SUM}"
+    if [[ "${EXPECTED_COMPOSER_SHA384_SUM}" != "${ACTUAL_COMPOSER_SHA384_SUM}" ]]; then
+      echo "Invalid composer-setup.php checksum" >&2
+      exit 1
+    fi
+    echo "composer-setup.php checksum matched"
+
     php composer-setup.php --install-dir /tmp
-    php -r "unlink('composer-setup.php');"
+    rm composer-setup.php
+
+    # Install PHP test dependencies.
     php /tmp/composer.phar global require phpunit/phpunit:9.5.9
   else
     # Workaround for https://github.com/Homebrew/homebrew-core/issues/41081
